language: go

#services:
  #- docker

go:
  - "1.9.x"
  #- "1.10.x"
  #- tip

#cache:
#  directories:
#  - node_modules

#matrix:
  #fast_finish: true
  #allow_failures:
    #- go: tip

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn

install:
  - make dependencies

jobs:
  include:
    # validate and build
    - stage: validate and build
      script:
        - make test
        - make lint
        - make coverage
        - make validate-commit
    - script:
        - make packages
      if: tag is blank
    # release to github
    - stage: release to github
      if: tag is present
      script:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          go: 1.9
    # echo
    - stage: echo
      script:
        - echo "HOLA"
    # push to dockerhub
    - stage: push to dockerhub
      if: tag is present
      script:
        - make build
        - make docker-push
